### ISSUE TITLE
Add version metadata to release config map

### ISSUE THREAD

**Issue by matzew** [knative-extensions/eventing-integrations#51]
For the image mapper config map, it would be nice to have some metadata

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
...
  labels:
    app.kubernetes.io/version: "SHA"
  annotations:
    knative.dev/example-checksum: "123456"
```

this would be similar to other resource.
