### ISSUE TITLE
[AWS S3 Source] Unuspported ignoreBody option

### ISSUE THREAD

**Issue by acolombier** [knative-extensions/eventing-integrations#77]
The `ignoreBody` doesn't seem to have any effect. Here is a minimal reproduction steps:

```yaml
apiVersion: sources.knative.dev/v1alpha1
kind: IntegrationSource
metadata:
  name: integration-source-aws-s3
spec:
  aws:
    s3:
      arn: "my-bucket"
      ignoreBody: true
      region: eu-west-1
    auth:
      secret:
        ref:
          name: "aws-s3-secret"
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
```

## Expect

Events without the S3 object content as message

## Actuall

Same than without the option, the S3 object content is used as message

version: latest
