### ISSUE TITLE
[FR][AWS] SUpport of IRSA

### ISSUE THREAD

**Issue by acolombier** [knative-extensions/eventing-integrations#78]
Currently, only static credentials are supported. In EKS, it exists a feature called [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) (IAM roles for service accounts), whihc will use k8s OIDC to assign credential to a pod. To use it, you simply need to use a service account with a specific annotation. `ContainerSource` already support passing a custom service account, however, the credentials are expected to be set via `CAMEL_KAMELET_AWS_..._ACCESSKEY and `CAMEL_KAMELET_AWS_..._SECRETKEY`.

With IRSA, the pod-identity controller will mutate the pod to inject the AWS credentials, like so:
```
    env:                                                                                                                                                                                                                                   
    - name: AWS_STS_REGIONAL_ENDPOINTS                                                                                                                                                                                                     
      value: regional                                                                                                                                                                                                                      
    - name: AWS_DEFAULT_REGION                                                                                                                                                                                                             
      value: eu-west-1                                                                                                                                                                                                                     
    - name: AWS_REGION                                                                                                                                                                                                                     
      value: eu-west-1                                                                                                                                                                                                            
    - name: AWS_ROLE_ARN                                                                                                                                                                                                                   
      value: arn:aws:iam::<AccountNumber>:role/my-role                                                                                                                                                    
    - name: AWS_WEB_IDENTITY_TOKEN_FILE                                                                                                                                                                                                    
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token   
```

AWS client will automatically use these, in absence of static credential.

Relates to https://github.com/knative/eventing/issues/8437 and potentially https://github.com/knative/eventing/issues/8544
